language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
 - composer self-update
 - composer install
 - wget https://github.com/antirez/redis/archive/2.8.20.tar.gz
 - mv 2.8.20.tar.gz redis-2.8.20.tar.gz
 - tar zxvf redis-2.8.20.tar.gz
 - cd redis-2.8.20
 - make
 - ./src/redis-server ./redis.conf >> /dev/null &
 - cd ..

before_script: phpenv config-add php.redis.ini

script: phpunit